# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sarah Ruckhaus
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  25. VDC specialist. Web development amateur. "Athlete." Data nerd.
baseurl: / # the subpath of your site, e.g. /blog
url: "sarahruckhaus.com" # the base hostname & protocol for your site
twitter_username: SarahRuckus
github_username:  ruckhaus
linkedin_username: sarahruckhaus

# Build settings
markdown: kramdown
