# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sarah's Domain
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sarah's personal website/blog. Mostly used to keep my web skills sharp but
  also to provide a home on the web for somem of my work and my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ruckhaus.github.io" # the base hostname & protocol for your site
twitter_username: SarahRuckus
github_username:  ruckhaus

# Build settings
markdown: kramdown
